CREATE TABLE IF NOT EXISTS guides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  pdf_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE guides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "guides_select_public" ON guides;
DROP POLICY IF EXISTS "guides_insert_public" ON guides;
DROP POLICY IF EXISTS "guides_update_public" ON guides;
DROP POLICY IF EXISTS "guides_delete_public" ON guides;

CREATE POLICY "guides_select_public"
ON guides FOR SELECT
TO public
USING (true);

CREATE POLICY "guides_insert_public"
ON guides FOR INSERT
TO public
WITH CHECK (true);

CREATE POLICY "guides_update_public"
ON guides FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

CREATE POLICY "guides_delete_public"
ON guides FOR DELETE
TO public
USING (true);
