CREATE TABLE IF NOT EXISTS lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic TEXT NOT NULL,
  rule TEXT NOT NULL,
  youtube_url TEXT NOT NULL,
  pdf_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "lessons_select_public" ON lessons;
DROP POLICY IF EXISTS "lessons_insert_public" ON lessons;
DROP POLICY IF EXISTS "lessons_update_public" ON lessons;
DROP POLICY IF EXISTS "lessons_delete_public" ON lessons;

CREATE POLICY "lessons_select_public"
ON lessons FOR SELECT
TO public
USING (true);

CREATE POLICY "lessons_insert_public"
ON lessons FOR INSERT
TO public
WITH CHECK (true);

CREATE POLICY "lessons_update_public"
ON lessons FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

CREATE POLICY "lessons_delete_public"
ON lessons FOR DELETE
TO public
USING (true);
